
all: hello

VPATH = .

HELLO_SRC = hello.c
hello: $(HELLO_SRC:%.c=%.o)

-include $(HELLO_SRC:%.c=%.d)

%.d: %.c
	$(CC) $(CFLAGS) -w -MM -MF $@ $<
	sed -i -e 's,\($*\.o\) *:,\1 $@ :,g' $@

clean:
	rm -f hello $(HELLO_SRC:%.c=%.o) $(HELLO_SRC:%.c=%.d)

debug-x86:
	[ -d debug ] || mkdir debug 
	make -C debug -f ../Makefile VPATH=.. CFLAGS=-g

debug-arm:
	[ -d debug ] || mkdir debug 
	make -C debug -f ../Makefile VPATH=.. CFLAGS=-g CC=arm-linux-gcc

