default: hello

HELLO_SRC = hello.c
hello: $(HELLO_SRC:%.c=%.o)
-include $(HELLO_SRC:%.c=%.d)

%.o: %.c
	$(COMPILE.c) -MMD -o $@ $<

clean:
	rm -f *.o *.d

distclean: clean
	rm hello

install:
	install -m 755 -D hello $(DESTDIR)/usr/bin/hello

