all: hello

HELLO_SRC = hello.c
hello: $(HELLO_SRC:%.c=%.o)
-include $(HELLO_SRC:%.c=%.d)

%.o: %.c
	$(COMPILE.c) -MMD -o $@ $<

clean:
	rm -f hello $(HELLO_SRC:%.c=%.o) $(HELLO_SRC:%.c=%.d)

.PHONY: debug-x86 debug-arm clean

debug-arm/Makefile:
	mkdir -p debug-arm
	echo 'all %:' >> debug-arm/Makefile
	echo '	make -f ../Makefile VPATH=.. CFLAGS=-g CC=arm-linux-gcc $$@' >> debug-arm/Makefile

debug-arm: debug-arm/Makefile
	make -C debug-arm

