default: hello

HELLO_SRC = hello.c
hello: $(HELLO_SRC:%.c=%.o)
-include $(HELLO_SRC:%.c=%.d)

%.o: %.c
	$(COMPILE.c) -MMD -o $@ $<

clean:
	rm -f *.o *.d

distclean: clean
	rm hello

install:
	install -m 755 -D hello $(DESTDIR)/usr/bin/hello

.PHONY: debug-arm

debug-arm/Makefile:
	mkdir -p debug-arm
	echo 'all %:' >> debug-arm/Makefile
	echo '	make -f ../Makefile VPATH=.. CFLAGS=-g CC=arm-linux-gcc $$@' >> debug-arm/Makefile

debug-arm: debug-arm/Makefile
	make -C debug-arm

